name: Generate sample apps' APKs and documentation

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Generate Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install python dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Generate API Reference
        run: python3 ./generateApiReference.py

      - name: Build MkDocs
        run: mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.4.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./site

  apk:
    name: Generate APKs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Hello-Vector APK
        run: ./gradlew :hello-vector:assembleDebug

      - name: Build Sample App APK
        run: ./gradlew :sampleapp:assembleDebug

      - name: Upload Hello-Vector APK
        uses: actions/upload-artifact@v1
        with:
          name: hello-vector
          path: hello-vector/build/outputs/apk/debug/hello-vector-debug.apk

      - name: Upload Sample App APK
        uses: actions/upload-artifact@v1
        with:
          name: sample-app
          path: sampleapp/build/outputs/apk/debug/sampleapp-debug.apk
